language: python

env:
  global:
    - DINAMO="dinamo"

install:
  - python -c "import os; print('1: ', os.environ['DINAMO'])"

script:
  - python -c "import os; print('1: ', os.environ.get('DINAMO'))"
