sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

env:
  global:
    - RUN_INTEGRATION_TESTS=1
    - STACK_ARGS=""
    - GITHUB_RELEASE_VERSION=1.2.0

matrix:
  include:
  # Build on linux
  - compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS in addition to Linux
  # (for now MacOS is unsupported: issue with static linking)
  - compiler: ": #stack default osx"
    os: osx

before_install:
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
- |
  set -ex
  stack --no-terminal setup --no-reinstall > /dev/null
  set +ex

script:
- |
  set -ex
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    # TODO: This build doesn't take that long so we likely don't need this
    # Plus it won't actually work since we don't save the cache on timeout
    (timeout 1800 stack --no-terminal install) || ([ $? = 124 ] && echo "Timed out after 30min so the build will have to be picked up next time")
  else
    (gtimeout 1800 stack --no-terminal install) || ([ $? = 124 ] && echo "Timed out after 30min so the build will have to be picked up next time")
  fi
  #stack --no-terminal install
  set +ex

after_success:
- | # Only release on tags
  if [ -n "$TRAVIS_TAG" ]; then
    travis_retry curl -L https://github.com/tfausak/github-release/releases/download/$GITHUB_RELEASE_VERSION/github-release-$TRAVIS_OS_NAME.gz | gunzip > github-release
    chmod a+x github-release
    stack exec -- cp $(which denv) .
    tar -czf denv.tar.gz denv
    ./github-release release --token=$GITHUB_TOKEN --owner=denibertovic --repo=denv --title=$TRAVIS_TAG --tag=$TRAVIS_TAG
    ./github-release upload --token=$GITHUB_TOKEN --owner=denibertovic --repo=denv --file=denv.tar.gz --tag=$TRAVIS_TAG --name=denv-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86_64.tar.gz
  fi

